dist: bionic 

language: c

compiler: gcc

before_install:
    - sudo add-apt-repository --yes ppa:vala-team
    - sudo apt-get update --quiet
    - sudo apt-get install --yes --force-yes valac libglib2.0-bin libglib2.0-dev libgtk-3-dev libgee-0.8-dev 
    - sudo apt-get install python3-pip python3-setuptools
    - sudo apt-get install meson 

install:
	#- python3 -m pip install -U --upgrade pip 
	#- wget https://github.com/mesonbuild/meson/releases/download/0.37.0/meson-0.37.0.tar.gz
	#- tar -xvf meson-0.37.0.tar.gz -C $HOME/.local/bin
	#- wget https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-linux.zip
	#- unzip ninja-linux.zip -d $HOME/.local/bin

script:
    - mkdir build 
    - meson build
    - ninja -C build
    # Test fails due to the nature of Gtk needing a screen. 
    #- ninja -C build test
