dist: trusty

language: c

compiler: gcc

before_install:
    - sudo add-apt-repository --yes ppa:vala-team
    - sudo apt-get update --quiet
    - sudo apt-get install --yes --force-yes meson ninja valac libglib2.0-bin libglib2.0-dev libgtk-3-dev 

script:
    - meson build
    - cd build 
    - ninja install
    - ninja test
