dist: trusty

language: c

compiler: gcc

before_install:
    - sudo add-apt-repository --yes ppa:vala-team
    - sudo apt-get update --quiet
    - sudo apt-get install --yes --force-yes ninja valac libglib2.0-bin libglib2.0-dev libgtk-3-dev 

install:
    - export NINJA_LATEST=$(curl -s https://api.github.com/repos/ninja-build/ninja/releases/latest | grep browser_download_url | cut -d '"' -f 4 | grep ninja-linux.zip)
    - wget "$NINJA_LATEST"
    - unzip -q ninja-linux.zip -d build
    - pip3 install meson

script:
    - meson build
    - ninja -C build
    - ninja -C build test
