all:
	valac cluster-list-parser.vala --pkg=gtk+-3.0 --pkg=gee-0.8
	valac cluster-list-parser2.vala --pkg=gtk+-3.0 --pkg=gee-0.8
	valac cluster-list-parser3.vala --pkg=gtk+-3.0 --pkg=gee-0.8
	valac cluster-list-parser4.vala --pkg=gtk+-3.0 --pkg=gee-0.8
